{{- if .Values.amaMetricsPrometheusConfigNodeWindows.enabled -}}
kind: ConfigMap
apiVersion: v1
metadata:
  name: ama-metrics-prometheus-config-node-windows
  namespace: kube-system
  labels:
    {{- include "azure-prometheus-config.labels" . | nindent 4 }}
data:
  prometheus-config: |
  {{- tpl .Values.amaMetricsPrometheusConfigNodeWindows.config . | nindent 4 }}
{{- end }}