apiVersion: v2
name: snapshot-controller
description: A Helm chart to deploy snapshot-controller
keywords:
  - snapshot-controller
maintainers:
  - name: ialejandro
    email: hello@ialejandro.rocks
    url: https://ialejandro.rocks
sources:
  - https://github.com/kubernetes-csi/external-snapshotter/tree/master/deploy/kubernetes/snapshot-controller
home: https://github.com/kubernetes-csi/external-snapshotter/tree/master
type: application
version: 1.0.0
appVersion: "6.2.1"
