# See https://github.com/helm/chart-testing#configuration
chart-dirs: charts
check-version-increment: true
debug: false
remote: origin
upgrade: true
validate-chart-schema: true
validate-maintainers: false
validate-yaml: true
excluded-charts: ["bigquery-exporter"]
