{{- if and .Values.serviceMonitor.enabled .Values.metrics.exporter.enabled }}
apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: {{ include "cp-schema-registry.fullname" . }}-server
  labels:
    {{- include "cp-schema-registry.labels" . | nindent 4 }}
spec:
  selector:
    matchLabels:
      {{- include "cp-schema-registry.selectorLabels" . | nindent 8 }}
  endpoints:
  - port: metrics
    interval: {{ .Values.serviceMonitor.interval | quote }}
    scrapeTimeout: {{ .Values.serviceMonitor.scrapeTimeout | quote }}
    {{- if .Values.serviceMonitor.metricRelabelings }}
    metricRelabelings:
    {{- toYaml .Values.serviceMonitor.metricRelabelings | nindent 4 }}
    {{- end }}
    {{- if .Values.serviceMonitor.relabelings }}
    relabelings:
    {{- toYaml .Values.serviceMonitor.relabelings | nindent 4 }}
    {{- end }}
{{- end }}
