apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "bigquery-exporter.fullname" . }}-sql-file
  labels:
    {{- include "bigquery-exporter.labels" . | nindent 4 }}
  {{- with .Values.sqlFile.annotations }}
  annotations:
    {{- toYaml . | nindent 4 }}
  {{- end }}
data:
  bigquery.sql: |-
  {{- .Values.sqlFile.query | nindent 6 -}}