# Default values for replika.
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.

## Provide a name in place of replika
nameOverride: ""

## Provide a name to substitute for the full names of resources
fullnameOverride: ""

## Provide desired replicas
replicaCount: 1

## Schedule job
schedule: "5 * * * *"

## Image of replika deployment
image:
  repository: devopsiaci/helm-release-cleaner
  tag: latest
  pullPolicy: IfNotPresent

imagePullSecrets: []
#  - name: ""

## Resource limits & requests
resources: {}
#  limits:
#    cpu: 100m
#    memory: 128Mi
#  requests:
#    cpu: 100m
#    memory: 128Mi

## Assign custom affinity rules
affinity: {}

## Define which Nodes the Pods are scheduled on
nodeSelector: {}
# project: common

## Pod's tolerations
tolerations: []
# - key: project
#   operator: Equal
#   value: "common"
#   effect: NoSchedule

# Text string with the namespace names where the cleaner will work
# If none is specified, by default it will be executed in the default namespace
# Example: "default, monitoring"
namespacesClean: "default"

# Exclusion of releases
# List of releases to be excluded by the cleaner
releasesExclude:
  enabled: false
  releases:
  - my-release
