apiVersion: v2
description: A Kubernetes operator to replicate resources across namespaces
type: application
maintainers:
  - name: ialejandro
    email: hello@ialejandro.rocks
    url: https://ialejandro.rocks
name: replika
sources:
  - https://github.com/prosimcorp/replika
version: 1.0.3
appVersion: "v0.3.0"
home: https://github.com/prosimcorp/replika
keywords:
- operator
- replika
