---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: {{ include "release-cleaner.name" . }}
  labels:
    {{- include "release-cleaner.labels" . | nindent 4 }}
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: {{ include "release-cleaner.name" . }}
subjects:
  - kind: ServiceAccount
    name: {{ include "release-cleaner.name" . }}
    namespace: "{{ .Release.Namespace }}"
