---
{{- if semverCompare ">=1.25-0" .Capabilities.KubeVersion.GitVersion }}
apiVersion: batch/v1
{{- else }}
apiVersion: batch/v1beta1
{{- end }}
kind: CronJob
metadata:
  name: {{ include "release-cleaner.name" . }}
  labels:
    {{- include "release-cleaner.labels" . | nindent 4 }}
spec:
  schedule: "{{ .Values.schedule }}"
  concurrencyPolicy: Replace
  failedJobsHistoryLimit: 2
  successfulJobsHistoryLimit: 10
  jobTemplate:
    spec:
      template:
        metadata:
          labels:
{{ include "release-cleaner.labels" . | indent 12 }}
{{- if .Values.podAnnotations }}
          annotations:
{{ toYaml .Values.podAnnotations | indent 8 }}
{{- end }}
        spec:
          serviceAccountName: {{ include "release-cleaner.name" . }}
          restartPolicy: Never
          {{- with .Values.imagePullSecrets }}
          imagePullSecrets:
            {{- toYaml . | nindent 10 }}
          {{- end }}
          containers:
          - name: {{ .Chart.Name }}
            image: "{{ .Values.image.repository }}:latest"
            imagePullPolicy: {{ .Values.image.pullPolicy }}
            command: ["/bin/bash", "/tmp/release-cleaner.sh"]
            volumeMounts:
            - name: {{ include "release-cleaner.name" . }}
              mountPath: /tmp/release-cleaner.sh
              subPath: release-cleaner.sh
            resources:
{{ toYaml .Values.resources | indent 14 }}
          {{- with .Values.nodeSelector }}
          nodeSelector:
            {{- toYaml . | nindent 12 }}
          {{- end }}
          {{- with .Values.affinity }}
          affinity:
            {{- toYaml . | nindent 12 }}
          {{- end }}
          {{- with .Values.tolerations }}
          tolerations:
            {{- toYaml . | nindent 12 }}
          {{- end }}
          volumes:
            - name: {{ include "release-cleaner.name" . }}
              configMap:
                name: {{ include "release-cleaner.name" . }}
                defaultMode: 0755
