---
apiVersion: v1
kind: ServiceAccount
metadata:
  labels:
    {{- include "release-cleaner.labels" . | nindent 4 }}
  name: {{ include "release-cleaner.name" . }}
  namespace: {{ .Values.namespace }}
