replicaCount: 1
fullnameOverride: opencti-ci

env:
  APP__ADMIN__PASSWORD: test
  APP__ADMIN__TOKEN: b1976749-8a53-4f49-bf04-cafa2a3458c1
  APP__BASE_PATH: "/"
  APP__TELEMETRY__METRICS__ENABLED: true
  ELASTICSEARCH__ENGINE_SELECTOR: elk
  ELASTICSEARCH__URL: http://opencti-ci-elasticsearch:9200
  MINIO__ENDPOINT: opencti-ci-minio
  RABBITMQ__HOSTNAME: opencti-ci-rabbitmq
  REDIS__HOSTNAME: opencti-ci-redis-master
  REDIS__MODE: single
  REDIS__PORT: 6379

testConnection: false

serviceMonitor:
  enabled: true

worker:
  enabled: false

elasticsearch:
  fullnameOverride: opencti-ci-elasticsearch

minio:
  fullnameOverride: opencti-ci-minio

rabbitmq:
  fullnameOverride: opencti-ci-rabbitmq
  auth:
    erlangCookie: b25c953e-2193-4b8e-9f3b-9a3a5ba76d75

redis:
  fullnameOverride: opencti-ci-redis
