replicaCount: 1
fullnameOverride: opencti-ci

env:
  APP__ADMIN__PASSWORD: test
  APP__ADMIN__TOKEN: b1976749-8a53-4f49-bf04-cafa2a3458c1
  APP__BASE_PATH: "/"
  MINIO__ENDPOINT: opencti-ci-minio
  ELASTICSEARCH__URL: http://opencti-ci-elasticsearch:9200
  ELASTICSEARCH__ENGINE_SELECTOR: elk
  RABBITMQ__HOSTNAME: opencti-ci-rabbitmq
  REDIS__HOSTNAME: opencti-ci-redis-master
  REDIS__PORT: 6379
  REDIS__MODE: single

testConnection: false

worker:
  enabled: false

elasticsearch:
  fullnameOverride: opencti-ci-elasticsearch

minio:
  fullnameOverride: opencti-ci-minio

rabbitmq:
  fullnameOverride: opencti-ci-rabbitmq

redis:
  fullnameOverride: opencti-ci-redis
