apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: {{ include "ecr-registry-custom.fullname" . }}
  namespace: {{ .Release.Namespace }}
rules:
- apiGroups: [""]
  resources: ["secrets"]
  verbs: ["delete", "create", "get"]