{{- if .Values.middleware.enabled }}
apiVersion: traefik.containo.us/v1alpha1
kind: Middleware
metadata:
  name: splunkrhinoheaders
spec:
  headers:
  {{- toYaml .Values.middleware.headers | nindent 4 }}
{{- end }}
