{{ if .Values.networkPolicies.create }}
{{ range .Values.networkPolicies.config }}
---
apiVersion: networking.k8s.io/v1
kind: NetworkPolicy
metadata:
  name: {{ .name }}
  namespace: {{ .namespace }}
{{- if .labels }}
  labels:
  {{- with .labels }}
    {{- toYaml . | nindent 4 }}
  {{- end }}
{{- end }}
{{- if .annotations }}
  annotations:
  {{- with .annotations }}
    {{- toYaml . | nindent 4 }}
  {{- end }}
{{- end }}
spec:
{{ toYaml .spec | indent 2 }}

{{ end }}
{{ end }}