{{ if .Values.secrets.create }}
{{ range $secrets := .Values.secrets.config }}
---
apiVersion: v1
kind: Secret
metadata:
  name: {{ .name }}
  namespace: {{ .namespace }}
type: {{ .type }}
data:
{{- range $key, $value := $secrets.data }}
  {{ $value.name }}: {{ $value.value | b64enc | quote }}
{{- end }}

{{ end }}
{{ end }}