{{ if .Values.VolumeSnapshotClass.create }}
{{ range .Values.VolumeSnapshotClass.config }}
---
apiVersion: snapshot.storage.k8s.io/v1 
kind: VolumeSnapshotClass 
metadata: 
  name: {{ .name }}
  labels:
  {{- with .labels }}
    {{- toYaml . | nindent 4 }}
  {{- end }}
driver: {{ .driver }}
deletionPolicy: {{ .deletionPolicy }}
parameters:
{{- with .parameters }}
  {{- toYaml . | nindent 2 }}
{{- end }}

{{ end }}
{{ end }}