{{ if .Values.volumeSnapshotClass.create }}
{{ range .Values.volumeSnapshotClass.config }}
---
apiVersion: snapshot.storage.k8s.io/v1 
kind: VolumeSnapshotClass 
metadata: 
  name: {{ .name }}
{{- if .labels }}
  labels:
  {{- with .labels }}
    {{- toYaml . | nindent 4 }}
  {{- end }}
{{- end }}
{{- if .annotations }}
  annotations:
  {{- with .annotations }}
    {{- toYaml . | nindent 4 }}
  {{- end }}
{{- end }}
driver: {{ .driver }}
deletionPolicy: {{ .deletionPolicy }}
{{- if .parameters }}
parameters:
{{- with .parameters }}
  {{- toYaml . | nindent 2 }}
{{- end }}
{{- end }}

{{ end }}
{{ end }}