apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "kafka-cruise-control.fullname" . }}-config
  labels:
    {{- include "kafka-cruise-control.labels" . | nindent 4 }}
data:
  cruise-control.properties: |
    {{- range $key, $value := .Values.config }}
      {{- $valueStr := printf "%v" $value }}
      {{- if and (regexMatch "^[0-9]+$" $valueStr) (lt (len $valueStr) 10) }}
        {{ $key }}={{ $valueStr }}
      {{- else if regexMatch "^[0-9]+\\.[0-9]+$" $valueStr }}
        {{ $key }}={{ printf "%.1f" $value }}
      {{- else if eq (typeOf $value) "float64" }}
        {{ $key }}={{ $value | int64 }}
      {{- else if eq (typeOf $value) "[]interface {}" }}
        {{ $key }}={{ $value | join "," }}
      {{- else }}
        {{ $key }}={{ $value }}
      {{- end }}
    {{- end }}
  capacityCores.json: |
    {
      "brokerCapacities":[
        {
          "brokerId": "-1",
          "capacity": {
            "DISK": {{ .Values.kafkaCluster.storage | int64 | quote }},
            "CPU": {"num.cores": {{ .Values.kafkaCluster.numCores | quote }}},
            "NW_IN": {{ .Values.kafkaCluster.networkIn | int64 | quote }},
            "NW_OUT": {{ .Values.kafkaCluster.networkOut | default .Values.kafkaCluster.networkIn | int64 | quote }}
          },
          "doc": "This is the default capacity. Capacity unit used for disk is in MB, cpu is in number of cores, network throughput is in KB."
        }
      ]
    }
  log4j.properties: |
    {{- range $key, $value := .Values.log4j }}
      {{ $key }}={{ $value }}
    {{- end }}
