apiVersion: v1
kind: Service
metadata:
  name: {{ include "kafka-cruise-control.fullname" . }}
  labels:
    {{- include "kafka-cruise-control.labels" . | nindent 4 }}
spec:
  type: {{ .Values.service.type }}
  ports:
    - port: {{ .Values.service.port }}
      targetPort: {{ .Values.service.targetPort | default .Values.service.port }}
      protocol: TCP
      name: http
  selector:
    {{- include "kafka-cruise-control.selectorLabels" . | nindent 4 }}
