sources:
  bitbucket-bot:
    kind: dockerimage
    spec:
      image: devopsiaci/bitbucket-bot
      architecture: linux/amd64
  ecr-token:
    kind: dockerimage
    spec:
      image: devopsiaci/ecr-token
      architecture: linux/amd64
  ssl-exporter:
    kind: dockerimage
    spec:
      image: ribbybibby/ssl-exporter
      architecture: linux/amd64
      versionFilter:
        kind: semver
conditions: {}
targets:
  bitbucket-bot:
    name: bump chart dependencies
    kind: yaml
    spec:
      file: charts/bitbucket-bot/Chart.yaml
      key: $.appVersion
    sourceid: bitbucket-bot
  bitbucket-bot-helm:
    name: Update bitbucket-bot helm chart
    kind: helmchart
    spec:
      name: charts/bitbucket-bot
      file: Chart.yaml
      key: $.version
      versionincrement: patch
    sourceid: bitbucket-bot

  ecr-token:
    name: bump chart dependencies
    kind: yaml
    spec:
      file: charts/ecr-token/Chart.yaml
      key: $.appVersion
    sourceid: ecr-token
  ecr-token-helm:
    name: Update ecr-token helm chart
    kind: helmchart
    spec:
      name: charts/ecr-token
      file: Chart.yaml
      key: $.version
      versionincrement: patch
    sourceid: ecr-token

  ssl-exporter:
    name: bump chart dependencies
    kind: yaml
    spec:
      file: charts/ssl-exporter/Chart.yaml
      key: $.appVersion
    sourceid: ssl-exporter
  ssl-exporter-helm:
    name: Update ssl-exporter helm chart
    kind: helmchart
    spec:
      name: charts/ssl-exporter
      file: Chart.yaml
      key: $.version
      versionincrement: patch
    sourceid: ssl-exporter
