sources:
  bigquery-exporter:
    kind: dockerimage
    spec:
      image: measurementlab/prometheus-bigquery-exporter
      architecture: linux/amd64
      versionFilter:
        kind: semver
  bitbucket-bot:
    kind: dockerimage
    spec:
      image: devopsiaci/bitbucket-bot
      architecture: linux/amd64
  cp-schema-registry:
    kind: dockerimage
    spec:
      image: devopsiaci/cp-schema-registry
      architecture: linux/amd64
  ecr-token:
    kind: dockerimage
    spec:
      image: devopsiaci/ecr-token
      architecture: linux/amd64
  ssl-exporter:
    kind: dockerimage
    spec:
      image: ribbybibby/ssl-exporter
      architecture: linux/amd64
      versionFilter:
        kind: semver
conditions: {}
targets:
  bitbucket-bot-helm:
    name: Update bitbucket-bot helm chart
    kind: helmchart
    spec:
      name: charts/bitbucket-bot
      file: Chart.yaml
      key: $.appVersion
      versionincrement: patch
    sourceid: bitbucket-bot
  bigquery-exporter-helm:
    name: Update bigquery-exporter helm chart
    kind: helmchart
    spec:
      name: charts/bigquery-exporter
      file: Chart.yaml
      key: $.appVersion
      versionincrement: patch
    sourceid: bigquery-exporter
  cp-schema-registry-helm:
    name: Update cp-schema-registry helm chart
    kind: helmchart
    spec:
      name: charts/cp-schema-registry
      file: Chart.yaml
      key: $.appVersion
      versionincrement: patch
    sourceid: cp-schema-registry
  ecr-token-helm:
    name: Update ecr-token helm chart
    kind: helmchart
    spec:
      name: charts/ecr-token
      file: Chart.yaml
      key: $.appVersion
      versionincrement: patch
    sourceid: ecr-token
  ssl-exporter-helm:
    name: Update ssl-exporter helm chart
    kind: helmchart
    spec:
      name: charts/ssl-exporter
      file: Chart.yaml
      key: $.appVersion
      versionincrement: patch
    sourceid: ssl-exporter
