# RISKIQ
# ref: https://github.com/OpenCTI-Platform/connectors/tree/master/external-import/riskiq
- name: riskiq
  enabled: true
  replicas: 1
  image: {}
  env:
    RISKIQ_BASE_URL: ""
    RISKIQ_USER: ""
    RISKIQ_PASSWORD: ""
    RISKIQ_INTERVAL_SEC: ""
    CONNECTOR_CONFIDENCE_LEVEL: ""
    CONNECTOR_ID: ""
    CONNECTOR_LOG_LEVEL: ""
    CONNECTOR_NAME: "RISKIQ"
    CONNECTOR_SCOPE: "riskiq"
    CONNECTOR_TYPE: EXTERNAL_IMPORT
    CONNECTOR_AUTO:  ""
