# VXVAULT
# ref: https://github.com/OpenCTI-Platform/connectors/tree/master/external-import/vxvault
- name: vxvault
  enabled: true
  replicas: 1
  image: {}
  env:
    VXVAULT_URL: ""
    VXVAULT_CREATE_INDICATORS: ""
    VXVAULT_INTERVAL: ""
    CONNECTOR_CONFIDENCE_LEVEL: ""
    CONNECTOR_ID: ""
    CONNECTOR_LOG_LEVEL: "" # Empty use global config
    CONNECTOR_UPDATE_EXISTING_DATA: ""
    CONNECTOR_NAME: "VX Vault URL list"
    CONNECTOR_SCOPE: "vxvault"
    CONNECTOR_TYPE: EXTERNAL_IMPORT
