# ALIEN VAULT
# ref: https://github.com/OpenCTI-Platform/connectors/tree/master/external-import/alienvault
- name: alienvault
  enabled: true
  replicas: 1
  image: {}
  env:
    CONNECTOR_CONFIDENCE_LEVEL: ""
    CONNECTOR_ID: ""
    CONNECTOR_UPDATE_EXISTING_DATA: ""
    CONNECTOR_LOG_LEVEL: "" # Empty use global config
    ALIENVAULT_BASE_URL: ""
    ALIENVAULT_API_KEY: ""
    ALIENVAULT_TLP: ""
    ALIENVAULT_CREATE_OBSERVABLES: ""
    ALIENVAULT_CREATE_INDICATORS: ""
    ALIENVAULT_PULSE_START_TIMESTAMP: ""
    ALIENVAULT_REPORT_TYPE: ""
    ALIENVAULT_REPORT_STATUS: ""
    ALIENVAULT_GUESS_MALWARE: ""
    ALIENVAULT_GUESS_CVE: ""
    ALIENVAULT_EXCLUDED_PULSE_INDICATOR_TYPES: ""
    ALIENVAULT_ENABLE_RELATIONSHIPS: ""
    ALIENVAULT_ENABLE_ATTACK_PATTERNS_INDICATES: ""
    ALIENVAULT_INTERVAL_SEC: ""
    CONNECTOR_NAME: "AlienVault"
    CONNECTOR_SCOPE: "alienvault"
    CONNECTOR_TYPE: EXTERNAL_IMPORT
