# INTEZER
# ref: https://github.com/OpenCTI-Platform/connectors/tree/master/internal-enrichment/intezer-sandbox
- name: intezer
  enabled: true
  replicas: 1
  image: {}
  env:
    INTEZER_SANDBOX_API_KEY: ""
    INTEZER_SANDBOX_MAX_TLP: ""
    INTEZER_SANDBOX_FAMILY_COLOR: ""
    INTEZER_SANDBOX_MALICIOUS_COLOR: ""
    INTEZER_SANDBOX_TRUSTED_COLOR: ""
    INTEZER_SANDBOX_UNKNOWN_COLOR: ""
    INTEZER_SANDBOX_SUSPICIOUS_COLOR: ""
    CONNECTOR_CONFIDENCE_LEVEL: ""
    CONNECTOR_ID: ""
    CONNECTOR_LOG_LEVEL: "" # Empty use global config
    CONNECTOR_NAME: "IntezerSandbox"
    CONNECTOR_SCOPE: "Artifact"
    CONNECTOR_TYPE: INTERNAL_ENRICHMENT
    CONNECTOR_AUTO:  ""
