# IMPORT DOCUMENT
# ref: https://github.com/OpenCTI-Platform/connectors/tree/master/internal-import-file/import-document
- name: import-document
  enabled: true
  replicas: 1
  image: {}
  env:
    CONNECTOR_CONFIDENCE_LEVEL: ""
    CONNECTOR_ID: ""
    CONNECTOR_LOG_LEVEL: "" # Empty use global config
    CONNECTOR_NAME: ImportDocument
    CONNECTOR_ONLY_CONTEXTUAL: ""
    IMPORT_DOCUMENT_CREATE_INDICATOR: ""
    CONNECTOR_SCOPE: application/pdf,text/plain,text/html
    CONNECTOR_VALIDATE_BEFORE_IMPORT: "true"
    CONNECTOR_TYPE: INTERNAL_IMPORT_FILE
