# Custom values for default-resources.
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.
---
namespaces:
  create: false
  name: []
#  - integration
#  - monitoring

quotas:
  create: false
  config: []
#    - namespace: integration
#      quota_requests_cpu: "4"
#      quota_requests_memory: "6Gi"
#      quota_limits_cpu: "4"
#      quota_limits_memory: "6Gi"
#    - namespace: monitoring
#      quota_requests_cpu: "2"
#      quota_requests_memory: "2Gi"
#      quota_limits_cpu: "2"
#      quota_limits_memory: "2Gi"

secrets:
  create: false
  config: []
#  - name: my-secret
#    namespace: my-namespace
#    type: Opaque
#    data:
#      - name: data-name
#        value: data-value

serviceAccounts:
  create: false
  config: []
#  - name: integration
#    namespace: integration
#    clusterRoleRules: []
#      - apiGroups: ["extensions", "app"]
#        resources: ["deployments"]
#        verbs: ["get", "list", "watch", "create", "update", "patch"]
#      - apiGroups: ["extensions", "app"]
#        resources: ["deployments"]
#        verbs: ["get", "list", "watch", "create", "update", "patch"]
#  - name: monitoring
#    namespace: monitoring
#    clusterRoleRules: []
#      - apiGroups: ["*"]
#        resources: ["*"]
#        verbs: ["get", "list"]

VolumeSnapshotClass:
  create: false
  config: []
#  - name: my-volume-snapshot-class
#    labels:
#      key: value
#    driver: my-driver
#    deletionPolicy: Retain
#    parameters:
#      tags: 'foo=aaa,bar=bbb'