{{- if .Values.env.APP__TELEMETRY__METRICS__ENABLED }}
apiVersion: v1
kind: Service
metadata:
  name: {{ include "opencti.fullname" . }}-worker
  labels:
    opencti.component: worker
    {{- include "opencti.labels" . | nindent 4 }}
spec:
  type: {{ .Values.service.type }}
  ports:
    - name: metrics
      port: {{ .Values.env.WORKER_PROMETHEUS_TELEMETRY_PORT | default 14269 }}
      targetPort: {{ .Values.env.WORKER_PROMETHEUS_TELEMETRY_PORT | default 14269 }}
      protocol: TCP
  selector:
    opencti.component: worker
    {{- include "opencti.selectorLabels" . | nindent 4 }}
{{- end }}
