---
apiVersion: v1
kind: ServiceAccount
metadata:
  labels:
{{ include "helm-release-cleaner.labels" . | indent 4 }}
  name: {{ include "helm-release-cleaner.name" . }}
  namespace: {{ .Values.namespace }}
