apiVersion: v2
name: steampipe
description: A Helm chart for Kubernetes to deploy Steampipe
type: application
version: 1.6.0
appVersion: "0.21.1"
home: https://github.com/devops-ia/helm-charts/tree/main/charts/steampipe
sources:
  - https://github.com/turbot/steampipe
maintainers:
  - name: amartingarcia
    url: https://github.com/devops-ia

dependencies:
  - name: oauth2-proxy
    version: "6.18.*"
    repository: https://oauth2-proxy.github.io/manifests/
    condition: oauth2Proxy.enabled
