apiVersion: v2
name: steampipe
description: A Helm chart for Kubernetes to deploy Steampipe
type: application
version: 1.0.0
appVersion: "0.20.2"
home: https://github.com/devops-ia/helm-charts/tree/main/charts/steampipe
sources:
  - https://github.com/turbot/steampipe
maintainers:
  - name: amartingarcia
    url: https://github.com/devops-ia
