{{- if .Values.extraConfig.configMaps.enabled }}
{{ range $secrets := .Values.extraConfig.configMaps.config }}
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ .name }}
data:
{{- range $key, $value := $secrets.data }}
  {{ $key }}: |-
{{ tpl $value $| indent 4 }}
{{- end }}

{{- end }}
{{- end }}