{{- if .Values.externalSecrets.externalSecret.enabled }}
{{ range $data := .Values.externalSecrets.externalSecret.config }}
---
apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: {{ .name }}
{{- with $data.annotations }}
  labels:
    {{- toYaml . | nindent 4 }}
{{- end }}
{{- with $data.annotations }}
  annotations:
    {{- toYaml . | nindent 4 }}
{{- end }}
{{- with $data.spec }}
spec:
  {{- toYaml . | nindent 2 }}
{{- end }}  
{{- end }}
{{- end }}