{{ if .Values.secrets }}
apiVersion: v1
kind: Secret
type: Opaque
metadata:
  name: {{ include "opencti.fullname" . }}-credentials
  labels:
    {{- include "opencti.labels" . | nindent 4 }}
  annotations:
    helm.sh/hook: "pre-install,pre-upgrade"
data:
  {{- range $key, $value := .Values.secrets }}
  {{ $key }}: {{ $value | b64enc }}
  {{- end }}
{{ end }}
