apiVersion: v1
kind: Service
metadata:
  name: {{ include "opencti.fullname" . }}-server
  labels:
    opencti.component: server
    {{- include "opencti.labels" . | nindent 4 }}
spec:
  type: {{ .Values.service.type }}
  ports:
    - port: {{ .Values.service.port }}
      targetPort: {{ .Values.service.targetPort | default .Values.service.port }}
      protocol: TCP
      name: http
      {{- if and (eq "NodePort" .Values.service.type) .Values.service.nodePort }}
      nodePort: {{ .Values.service.nodePort }}
      {{- end }}
    {{- range $port := .Values.service.extraPorts }}
    - name: {{ $port.name }}
      port: {{ $port.port }}
      targetPort: {{ $port.targetPort }}
      protocol: TCP
    {{- end }}
  selector:
    opencti.component: server
    {{- include "opencti.selectorLabels" . | nindent 4 }}
