name: Auto-assign Issue
on:
  issues:
    types: [opened]
  pull_request_target:
    types: [opened, ready_for_review]
jobs:
  run:
    runs-on: ubuntu-latest
    permissions:
      issues: write
      pull-requests: write

    steps:
      - name: 'auto-assign issue'
        uses: pozil/auto-assign-issue@v2
        with:
          repo-token: ${{ secrets.PAT_GITHUB }}
          teams: devops-ia
