apiVersion: v2
name: splunk
description: A Helm chart to deploy Splunk standalone
keywords:
  - splunk
maintainers:
  - name: ialejandro
    email: hello@ialejandro.rocks
    url: https://ialejandro.rocks
home: https://www.splunk.com/
type: application
version: 1.0.0
appVersion: "9.0.0"
