{{- if .Values.rbac.enabled }}
kind: ClusterRoleBinding
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: {{ include "snapshot-controller.fullname" . }}-role
subjects:
  - kind: ServiceAccount
    name: {{ include "snapshot-controller.serviceAccountName" . }}
    namespace: {{ .Release.Namespace }}
roleRef:
  kind: ClusterRole
  name: {{ include "snapshot-controller.fullname" . }}-runner
  apiGroup: rbac.authorization.k8s.io
{{- end }}